# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Allison McCartney
email:  allison.n.mccartney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Journalist, coder, designer, artist


baseurl:  "" # the subpath of your site, e.g. /blog
url:      "" # the base hostname & protocol for your site

twitter_username:       anmccartney
github_username:        amccartney
linkedin_username:      allisonmccartney
google_plus_username:   
facebook_username:      

google_analytics:   UA-73659012-1

port: 4001

# Build settings
markdown: kramdown
